SQL :
  addr : 127.0.0.1
  port : 3306
  user : root  # 数据库账号
  pass : P110040593abc # 数据库密码
  database : task_manage # 数据库名称
  maxIdle: 20 # 空闲连接池数量
  maxOpen: 100 # 最大连接数
  maxLife: 30 # 连接后空闲状态维持时间(秒)


Redis:
  addr : 127.0.0.1:6379  # redis地址和端口
# password : "myredis1234"#
  db : 2 # 数据库编号
  dialTimeout : 3 # 连接超时时间(秒)